# use PowerShell instead of sh:
set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

build:
    cargo build

test:
    cargo test

run:
    cargo run


@linux-build:
    cross build --target x86_64-pc-windows-gnu
    mv target/x86_64-pc-windows-gnu/debug/creator.exe .