
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AT BLAND CLOSEBRACKET DOT HOUSE IDENTIFIER OPENBRACKET PUBTASK ROOMprogram : statementstatement : HOUSE IDENTIFIER DOT ROOM IDENTIFIER OPENBRACKET CLOSEBRACKET\n                 | PUBTASK AT IDENTIFIER BLAND IDENTIFIER OPENBRACKET CLOSEBRACKET'
    
_lr_action_items = {'HOUSE':([0,],[3,]),'PUBTASK':([0,],[4,]),'$end':([1,2,15,16,],[0,-1,-2,-3,]),'IDENTIFIER':([3,6,9,10,],[5,8,11,12,]),'AT':([4,],[6,]),'DOT':([5,],[7,]),'ROOM':([7,],[9,]),'BLAND':([8,],[10,]),'OPENBRACKET':([11,12,],[13,14,]),'CLOSEBRACKET':([13,14,],[15,16,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement','program',1,'p_program','transpiler3.0.py',40),
  ('statement -> HOUSE IDENTIFIER DOT ROOM IDENTIFIER OPENBRACKET CLOSEBRACKET','statement',7,'p_statement','transpiler3.0.py',44),
  ('statement -> PUBTASK AT IDENTIFIER BLAND IDENTIFIER OPENBRACKET CLOSEBRACKET','statement',7,'p_statement','transpiler3.0.py',45),
]
